// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OdectyStat1.DataLayer;

#nullable disable

namespace OdectyStat1.Migrations.Gauge
{
    [DbContext(typeof(GaugeDbContext))]
    partial class GaugeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OdectyStat1.Business.Gauge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HomeassistantId")
                        .HasColumnType("int");

                    b.Property<decimal>("InitialValue")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("LastValue")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal?>("MaxValuePerHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gauge");
                });

            modelBuilder.Entity("OdectyStat1.Business.GaugeMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("CurrentValue")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("GaugeId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastMeasurementDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MeasurementDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.HasKey("Id");

                    b.HasIndex("GaugeId");

                    b.ToTable("GaugeMeasurement");
                });

            modelBuilder.Entity("OdectyStat1.Entities.GaugeMeasuerementStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CurrentValue")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("GaugeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MeasurementDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.HasKey("Id");

                    b.HasIndex("GaugeId");

                    b.ToTable("GaugeMeasuerementStatistics");
                });

            modelBuilder.Entity("OdectyStat1.Business.GaugeMeasurement", b =>
                {
                    b.HasOne("OdectyStat1.Business.Gauge", null)
                        .WithMany("Measurements")
                        .HasForeignKey("GaugeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OdectyStat1.Entities.GaugeMeasuerementStatistics", b =>
                {
                    b.HasOne("OdectyStat1.Business.Gauge", null)
                        .WithMany("MeasurementsStatistics")
                        .HasForeignKey("GaugeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OdectyStat1.Business.Gauge", b =>
                {
                    b.Navigation("Measurements");

                    b.Navigation("MeasurementsStatistics");
                });
#pragma warning restore 612, 618
        }
    }
}
