// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OdectyStat1.DataLayer;

#nullable disable

namespace OdectyStat1.Migrations.Diagnostics
{
    [DbContext(typeof(DiagDbContext))]
    [Migration("20260623205927_AddFileAndTransferDiagnostics")]
    partial class AddFileAndTransferDiagnostics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OdectyStat1.Business.FileDiagnostic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("numeric")
                        .HasColumnName("confidence");

                    b.Property<decimal?>("CorrectedValue")
                        .HasColumnType("numeric")
                        .HasColumnName("corrected_value");

                    b.Property<decimal>("CorrelationId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("FilePath")
                        .HasColumnType("text")
                        .HasColumnName("file_path");

                    b.Property<int>("GaugeId")
                        .HasColumnType("integer")
                        .HasColumnName("gauge_id");

                    b.Property<decimal?>("RecognizedValue")
                        .HasColumnType("numeric")
                        .HasColumnName("recognized_value");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CorrelationId" }, "ix_file_diagnostics_correlation_id");

                    b.HasIndex(new[] { "Timestamp" }, "ix_file_diagnostics_timestamp");

                    b.ToTable("file_diagnostics", (string)null);
                });

            modelBuilder.Entity("OdectyStat1.Business.GarageDiagnostic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DoorCycles")
                        .HasColumnType("integer")
                        .HasColumnName("door_cycles");

                    b.Property<int>("FreeRam")
                        .HasColumnType("integer")
                        .HasColumnName("free_ram");

                    b.Property<int>("LoopMaxMs")
                        .HasColumnType("integer")
                        .HasColumnName("loop_max_ms");

                    b.Property<int>("MqttReconnects")
                        .HasColumnType("integer")
                        .HasColumnName("mqtt_reconnects");

                    b.Property<byte>("ResetReason")
                        .HasColumnType("smallint")
                        .HasColumnName("reset_reason");

                    b.Property<short?>("Rssi")
                        .HasColumnType("smallint")
                        .HasColumnName("rssi");

                    b.Property<byte>("SensorErrors")
                        .HasColumnType("smallint")
                        .HasColumnName("sensor_errors");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<long>("UptimeMinutes")
                        .HasColumnType("bigint")
                        .HasColumnName("uptime_minutes");

                    b.Property<int>("WifiReconnects")
                        .HasColumnType("integer")
                        .HasColumnName("wifi_reconnects");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Timestamp" }, "ix_garage_diagnostics_timestamp");

                    b.ToTable("garage_diagnostics", (string)null);
                });

            modelBuilder.Entity("OdectyStat1.Business.HeaterDiagnostic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("FreeRam")
                        .HasColumnType("integer")
                        .HasColumnName("free_ram");

                    b.Property<int>("LoopMaxMs")
                        .HasColumnType("integer")
                        .HasColumnName("loop_max_ms");

                    b.Property<int>("MqttReconnects")
                        .HasColumnType("integer")
                        .HasColumnName("mqtt_reconnects");

                    b.Property<byte>("ResetReason")
                        .HasColumnType("smallint")
                        .HasColumnName("reset_reason");

                    b.Property<short?>("Rssi")
                        .HasColumnType("smallint")
                        .HasColumnName("rssi");

                    b.Property<int>("SensorErrors")
                        .HasColumnType("integer")
                        .HasColumnName("sensor_errors");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<long>("UptimeMinutes")
                        .HasColumnType("bigint")
                        .HasColumnName("uptime_minutes");

                    b.Property<int>("WifiReconnects")
                        .HasColumnType("integer")
                        .HasColumnName("wifi_reconnects");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Timestamp" }, "ix_heater_diagnostics_timestamp");

                    b.ToTable("heater_diagnostics", (string)null);
                });

            modelBuilder.Entity("OdectyStat1.Business.LSSensorDiagnostic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("FreeRam")
                        .HasColumnType("integer")
                        .HasColumnName("free_ram");

                    b.Property<int>("LoopMaxMs")
                        .HasColumnType("integer")
                        .HasColumnName("loop_max_ms");

                    b.Property<int>("MqttFailCount")
                        .HasColumnType("integer")
                        .HasColumnName("mqtt_fail_count");

                    b.Property<byte>("ResetReason")
                        .HasColumnType("smallint")
                        .HasColumnName("reset_reason");

                    b.Property<short?>("Rssi")
                        .HasColumnType("smallint")
                        .HasColumnName("rssi");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<long>("UptimeMinutes")
                        .HasColumnType("bigint")
                        .HasColumnName("uptime_minutes");

                    b.Property<int>("WifiReconnects")
                        .HasColumnType("integer")
                        .HasColumnName("wifi_reconnects");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Timestamp" }, "ix_ls_sensor_diagnostics_timestamp");

                    b.ToTable("ls_sensor_diagnostics", (string)null);
                });

            modelBuilder.Entity("OdectyStat1.Business.TransferDiagnostic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BytesSent")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes_sent");

                    b.Property<decimal>("CorrelationId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("correlation_id");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ms");

                    b.Property<int>("GaugeId")
                        .HasColumnType("integer")
                        .HasColumnName("gauge_id");

                    b.Property<short>("HttpCode")
                        .HasColumnType("smallint")
                        .HasColumnName("http_code");

                    b.Property<long>("ImgSize")
                        .HasColumnType("bigint")
                        .HasColumnName("img_size");

                    b.Property<short>("Rssi")
                        .HasColumnType("smallint")
                        .HasColumnName("rssi");

                    b.Property<byte>("SchemaVer")
                        .HasColumnType("smallint")
                        .HasColumnName("schema_ver");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<byte>("TryCount")
                        .HasColumnType("smallint")
                        .HasColumnName("try_count");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CorrelationId" }, "ix_transfer_diagnostics_correlation_id");

                    b.HasIndex(new[] { "Timestamp" }, "ix_transfer_diagnostics_timestamp");

                    b.ToTable("transfer_diagnostics", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
