// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OdectyStat1.DataLayer;

#nullable disable

namespace OdectyStat1.Migrations.Diagnostics
{
    [DbContext(typeof(DiagDbContext))]
    partial class DiagDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OdectyStat1.Business.HeaterDiagnostic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("FreeRam")
                        .HasColumnType("integer")
                        .HasColumnName("free_ram");

                    b.Property<int>("LoopMaxMs")
                        .HasColumnType("integer")
                        .HasColumnName("loop_max_ms");

                    b.Property<int>("MqttReconnects")
                        .HasColumnType("integer")
                        .HasColumnName("mqtt_reconnects");

                    b.Property<byte>("ResetReason")
                        .HasColumnType("smallint")
                        .HasColumnName("reset_reason");

                    b.Property<int>("SensorErrors")
                        .HasColumnType("integer")
                        .HasColumnName("sensor_errors");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<long>("UptimeMinutes")
                        .HasColumnType("bigint")
                        .HasColumnName("uptime_minutes");

                    b.Property<int>("WifiReconnects")
                        .HasColumnType("integer")
                        .HasColumnName("wifi_reconnects");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Timestamp" }, "ix_heater_diagnostics_timestamp");

                    b.ToTable("heater_diagnostics", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
