name: Deploy na Windows službu

on:
  workflow_dispatch:
    inputs:
      artifact_run_id:
        description: 'ID běhu workflow s artefaktem'
        required: true
        type: string
      artifact_name:
        description: 'Název artefaktu'
        required: false
        default: 'IoTDeployer'
        type: string
      environment:
        required: true
        type: choice
        options:
          - Home

permissions:
  contents: read
  actions: read
  deployments: write

jobs:
  deploy:
    uses: Zefek/GithubActions/.github/workflows/windows-service-deploy.yml@main
    with:
      environment:     ${{ inputs.environment }}
      artifact_run_id: ${{ inputs.artifact_run_id }}
      artifact_name:   ${{ inputs.artifact_name }}
      device_name:     Odecty
    secrets: inherit
